#!/usr/bin/env bash

# Generated by running `printf "$(heroku autocomplete:script bash)" >> ~/.bash_profile.d/01_heroku_autocomplete.sh`
# https://devcenter.heroku.com/articles/heroku-cli-autocomplete
# shellcheck disable=SC1090

# heroku autocomplete setup
HEROKU_AC_BASH_SETUP_PATH=/Users/craiga/Library/Caches/heroku/autocomplete/bash_setup && test -f $HEROKU_AC_BASH_SETUP_PATH && source $HEROKU_AC_BASH_SETUP_PATH;
